<?php

namespace app\admin\model\lottery;

use think\Model;
use think\worker\Server;


class Orders extends Model
{

    
   // protected $wanfa;
    

    // 表名
    protected $name = 'bet';
    
    // 自动写入时间戳字段
    protected $autoWriteTimestamp = false;

    // 定义时间戳字段名
    protected $createTime = false;
    protected $updateTime = false;
    protected $deleteTime = false;

    // 追加属性
    protected $append = [
        'status_text',
        'endtime_text',
//        'wanfastr',
//        'zhudanstr'
    ];
//    protected function initialize()
//    {
//        parent::initialize(); // TODO: Change the autogenerated stub
//        $this->wanfa=
//    }


    public function getWanfaAttr($value,$data)
    {
        $wanfa=config('apiwanfa.'.$data['csk']);
        //dump($wanfa);die;
        return $wanfa[$value]['name'];
    }
    public function getZhudanAttr($value,$data)
    {
        $wanfa=config('apiwanfa.'.$data['csk']);
        if(array_key_exists($value,$wanfa[$data['wanfa']])){
            return $wanfa[$data['wanfa']][$value];
        }
        return $value;
    }

    public function getStatusList()
    {
        return ['0' => __('Status 0'), '1' => __('Status 1')];
    }


    public function getStatusTextAttr($value, $data)
    {
        $value = $value ? $value : (isset($data['status']) ? $data['status'] : '');
        $list = $this->getStatusList();
        return isset($list[$value]) ? $list[$value] : '';
    }


    public function getEndtimeTextAttr($value, $data)
    {
        $value = $value ? $value : (isset($data['endtime']) ? $data['endtime'] : '');
        return is_numeric($value) ? date("Y-m-d H:i:s", $value) : $value;
    }

    protected function setEndtimeAttr($value)
    {
        return $value === '' ? null : ($value && !is_numeric($value) ? strtotime($value) : $value);
    }


}
