<?php
/**
 * Created by PhpStorm.
 * User: LazyQ
 * Date: 2020-04-29
 * Time: 18:58
 */

return [
    '21'=>[
        'shuangmian'=>[
            'da'=>1.97,
            'xiao'=>1.97,
            'dan'=>1.97,
            'shuang'=>1.97,
            'zhi'=>1.97,
            'he'=>1.97,

        ],
        'yivwu'=>[
            'long'=>1.99,
            'hu'=>1.99,
            'he'=>9.89,
        ],
        'wuxuanyi'=>2.25,
    ],
    '17'=>[
        'guanjun'=>9.89,
        'guanyahe'=>[
            'hedan'=>1.78,
            'heshuang'=>2.12,
            'heda'=>2.12,
            'hexiao'=>1.78,
        ],
        'shuangmian'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
    ],
    '20'=>[
        'shuangmian'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
        'shengxiao'=>[
            'shu'=>9.46,
            'niu'=>11.8,
            'hu'=>11.8,
            'tu'=>11.8,
            'long'=>11.8,
            'she'=>11.8,
            'ma'=>11.8,
            'yang'=>11.8,
            'hou'=>11.8,
            'ji'=>11.8,
            'gou'=>11.8,
            'zhu'=>11.8,
        ],
        'sebo'=>[
            'hong'=>2.82,
            'lv'=>2.97,
            'lan'=>2.97,
        ]
    ],
    '32'=>[
        'zonghe'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
        'sanjun'=>1.97,
        'duanpai'=>12.4,

    ],
    '3'=>[
        'zonghe'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
        'yiliangmian'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
        'baliangmian'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
    ],
    '11'=>[
        'zonghe'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
        'yiliangmian'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
        'baliangmian'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
    ],
    '35'=>[
        'zonghe'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
        'yiliangmian'=>[
            'dan'=>1.97,
            'shuang'=>1.97,
            'da'=>1.97,
            'xiao'=>1.97,
        ],
        'wuxuanyi'=>2.00,
    ],

];