<?php


return [
    '21'=>[
        'shuangmian'=>[
            'name'=>'一球两面',
            'da'=>'大',
            'xiao'=>'小',
            'dan'=>'单',
            'shuang'=>'双',
            'zhi'=>'质',
            'he'=>'合',
        ],

        'yivwu'=>[
            'name'=>'第一球vs第五球',
            'long'=>'龙',
            'hu'=>'虎',
            'he'=>'和',
        ],
        'wuxuanyi'=>[
            'name'=>'五选一',
        ]
    ],
    '17'=>[
        'guanjun'=>[
            'name'=>'冠军'
        ],
        'guanyahe'=>[
            'name'=>'冠亚和',
            'hedan'=>'和单',
            'heshuang'=>'和双',
            'heda'=>'和大',
            'hexiao'=>'和小',
        ],
        'shuangmian'=>[
            'name'=>'冠军双面',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',],

    ],
    '20'=>[
        'shuangmian'=>[
            'name'=>'特码两面',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
        'shengxiao'=>[
            'name'=>'特码生肖',
            'shu'=>'鼠',
            'niu'=>'牛',
            'hu'=>'虎',
            'tu'=>'兔',
            'long'=>'龙',
            'she'=>'蛇',
            'ma'=>'马',
            'yang'=>'羊',
            'hou'=>'猴',
            'ji'=>'鸡',
            'gou'=>'狗',
            'zhu'=>'猪',
        ],
        'sebo'=>[
            'name'=>'特码色波',
            'hong'=>'红波',
            'lv'=>'绿波',
            'lan'=>'蓝波',
        ]
    ],
    '32'=>[
        'zonghe'=>[
            'name'=>'总和',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
        'sanjun'=>[
            'name'=>'三军'
        ],
        'duanpai'=>[
            'name'=>'短牌'
        ],

    ],
    '3'=>[
        'zonghe'=>[
            'name'=>'总和',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
        'yiliangmian'=>[
            'name'=>'第一球两面',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
        'baliangmian'=>[
            'name'=>'第八球两面',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
    ],
    '11'=>[
        'zonghe'=>[
            'name'=>'总和',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
        'yiliangmian'=>[
            'name'=>'第一球两面',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
        'baliangmian'=>[
            'name'=>'第八球两面',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
    ],
    '35'=>[
        'zonghe'=>[
            'name'=>'总和',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
        'yiliangmian'=>[
            'name'=>'第一球两面',
            'dan'=>'单',
            'shuang'=>'双',
            'da'=>'大',
            'xiao'=>'小',
        ],
        'wuxuanyi'=>[
            'name'=>'五选一',
        ],
    ]

];